# Generated by Django 2.0 on 2019-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=5000)),
                ('body', models.CharField(max_length=500000)),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
    ]
