# Generated by Django 2.0 on 2019-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191110_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='link',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
