# Generated by Django 2.0 on 2019-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191110_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_picture',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
