# Generated by Django 2.0 on 2019-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tweet_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='byline',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
